### ISSUE TITLE
Changing SMTP/e-mail details after Docker install

### ISSUE THREAD

**Issue by bpr-sulli** [arachnys/cabot#623]
Hi,

I installed Cabot with Docker but I don't get any e-mail alerts. There doesn't seem to be any configurable settings for the e-mail alert plugin in Cabot or the Django admin. How can I change/add/update my e-mail settings (SMTP server, etc)? None of the docker containers appear to have an env.conf file.

If I need to re-run the container/image, which one(s)? Can I keep the database container as-is so I don't lose my configured checks?

Thanks,

**Comment by hartwork** [comment]
Based on this output ..
```
# egrep '\.env|^  [^ ]+' docker-compose.yml 
  web:
      - conf/development.env
  worker:
      - conf/development.env
  beat:
      - conf/development.env
  redis:
  db:
  datavolume:
```
.. I believe you can keep your database and need to shutdown-rebuild-start `web`, `worker` and `beat` only.
